# docker-compose.yml
version: '3.8'

services:
  jupiter:
    image: jupiter:V3
    ports:
      - "83:83"
    restart: unless-stopped
     networks:
      cosmos:
        ipv4_address: 192.168.95.31

networks:
  cosmos:
    external: true
    name: cosmos
